# -*- coding: utf-8 -*-
"""Charts and Graphs for COMMUNITY POLICING AS A PANACEA FOR CRIME REDUCTION IN NIGERIA: MIRRORING THE PRACTICES OF THE UNITED KINGDOM .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YTztQ16GHFrsfvst_eo2evUCvu2eE9pC

# **A bar chart comparing the crime rates between Nigeria and the United Kingdom**
"""

import matplotlib.pyplot as plt

# Data
data = {
    'Level of crime': (70.63, 51.77),
    'Crime increasing in the past 3 years': (64.44, 64.06),
    'Worries home broken and things stolen': (63.35, 43.01),
    'Worries being mugged or robbed': (69.07, 44.13),
    'Worries car stolen': (61.35, 36.57),
    'Worries things from car stolen': (67.45, 43.49),
    'Worries attacked': (61.49, 45.42),
    'Worries being insulted': (55.55, 49.61),
    'Worries being subject to a physical attack because of your skin color, ethnic origin, gender or religion': (44.93, 33.08),
    'Problem people using or dealing drugs': (63.69, 62.30),
    'Problem property crimes such as vandalism and theft': (69.02, 53.44),
    'Problem violent crimes such as assault and armed robbery': (72.76, 44.84),
    'Problem corruption and bribery': (85.07, 32.92),
}

# Plotting
fig, ax = plt.subplots(figsize=(14, 8))
categories = list(data.keys())
nigeria_data = [item[0] for item in data.values()]
uk_data = [item[1] for item in data.values()]

y = range(len(categories))
height = 0.35

ax.barh([i - height / 2 for i in y], nigeria_data, height, label='Nigeria')
ax.barh([i + height / 2 for i in y], uk_data, height, label='United Kingdom')

ax.set_xlabel('Crime Rate')
ax.set_title('Crime Rate Comparison: Nigeria vs United Kingdom')
ax.set_yticks(y)
ax.set_yticklabels(categories)
ax.legend()

plt.tight_layout()
plt.show()

"""# **Challenges Facing Nigerian Polic Force**"""

import matplotlib.pyplot as plt
import numpy as np

# Data
ranks = [1, 2, 3, 4]
obstacles = [
    'Insufficient financing',
    'Type of training and qualifications',
    'Lack of adequate personnel',
    'Lack of appropriate equipment',
]

# Plotting
fig, ax = plt.subplots(figsize=(10, 6))
bars = ax.barh(ranks, sorted(ranks, reverse=True), tick_label=obstacles)

# Set color gradient
for i, bar in enumerate(bars):
    bar.set_color(plt.cm.viridis(i / len(ranks)))

ax.set_xlabel('Relative Importance')
ax.set_ylabel('Rank')
ax.set_title('Challenges Facing the Nigerian Police Force')
ax.set_yticks(ranks)
ax.invert_yaxis()  # Invert the y-axis to display rank 1 at the top

plt.tight_layout()
plt.show()